// <auto-generated />
namespace Buy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FavoriteAddType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FavoriteAddType));
        
        string IMigrationMetadata.Id
        {
            get { return "201710270326596_FavoriteAddType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
